# Generated by Django 4.0.4 on 2022-05-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snacks',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
